### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [NicolaiRuckel/nidoranarion#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license or a screen shot.

Please add a LICENSE - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com). Also, please add a screen shot so that people can see what it looks like without having to install it.

**Comment by NicolaiRuckel** [comment]
Done.
